/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.interfaces;

import java.util.regex.Pattern;

import javax.swing.JOptionPane;

import com.models.LoggedUser;
import com.models.RegisteredUser;
import com.models.User;
import com.rmi.client.Client;
import com.rmi.service.interfaces.FireAlarmServiceInterface;

/**
 *
 * @author Akila Mihiranga
 */
public class userRegisterFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form userRegisterFrame
     */
	//create constructor.
	//call getFireAlarmServiceInterface client object to get rmi server connection.
	
	private FireAlarmServiceInterface fireAlarmServiceInterface = null;
	private Client client = new Client();
	
    public userRegisterFrame() {
        initComponents();
        this.fireAlarmServiceInterface = client.getFireAlarmServiceInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRegName = new javax.swing.JTextField();
        txtRegEmail = new javax.swing.JTextField();
        txtRegMobile = new javax.swing.JTextField();
        txtRegPassword = new javax.swing.JPasswordField();
        registerUserBtn = new javax.swing.JButton();
        loginUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/client/img/alarm.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 46)); // NOI18N
        jLabel2.setText("REGISTer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        jLabel3.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Mobile");

        jLabel6.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Password");

        txtRegName.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N

        txtRegEmail.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N

        txtRegMobile.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N

        txtRegPassword.setFont(new java.awt.Font("Open Sans Semibold", 0, 18)); // NOI18N

        registerUserBtn.setBackground(new java.awt.Color(51, 102, 255));
        registerUserBtn.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        registerUserBtn.setText("REGISTER");
        registerUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserBtnActionPerformed(evt);
            }
        });

        loginUserBtn.setBackground(new java.awt.Color(51, 102, 255));
        loginUserBtn.setFont(new java.awt.Font("Open Sans Semibold", 0, 24)); // NOI18N
        loginUserBtn.setText("LOGIN");
        loginUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(txtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(txtRegMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(registerUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(loginUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(registerUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(loginUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserBtnActionPerformed
    	//User click login button,then dispose the this register interface and show login form user interface.
        userLoginFrame userLog = new userLoginFrame();
        userLog.setVisible(true);
        userLog.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_loginUserBtnActionPerformed

    private void registerUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserBtnActionPerformed
    	//get name input field value and assign into variable.
    	String name = txtRegName.getText();
    	//get email input field value and assign into variable.
    	String email = txtRegEmail.getText();
    	//get mobile number input field value and assign into variable.
    	String mobile = txtRegMobile.getText();
    	//get password input field value and assign into variable.
        String password = String.valueOf(txtRegPassword.getPassword());
    	
        //if any input field is empty,show message error message.
        if(name.trim().equals("") || email.trim().equals("") || mobile.trim().equals("") || password.trim().equals("")){
        	JOptionPane.showMessageDialog(rootPane, "One Or More Fields Are Empty", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
        //if email pattern is wrong ,show error message.
        else if(!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))){
            JOptionPane.showMessageDialog(rootPane, "Please enter valid Email", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
        //if mobile number has more than 10 number or string values,show error message.
        else if(!(Pattern.matches("^[0-9]{10}+$", mobile))){
            JOptionPane.showMessageDialog(rootPane, "Please enter valid phone Number", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
        	//create new User object
        	User user = new User();
        	//set name
        	user.setName(name);
        	//set email
    		user.setEmail(email);
    		//set mobile number
    		user.setMobile(mobile);
    		//set password
    		user.setPassword(password);
        	
        	try {
        		//create RegisteredUser for get responses.
        		//call the register method in the remote interface and pass User object.
        		RegisteredUser registeredUser = this.fireAlarmServiceInterface.register(user);
        		//then get the status and assign in to variable.
            	String checkStatus = registeredUser.getStatus();
            	
            	//if status "Success",that means User registered successful.
            	//redirected to main login interface.
            	if(checkStatus.equalsIgnoreCase("Success")) {
                    this.setVisible(false);
                    String[] regUser = new String[4];
                    regUser[0] = user.getName(); //get user Name
                    regUser[1] = user.getEmail(); //get user email
                    regUser[2] = user.getMobile(); //get user mobile
                    regUser[3] = user.getPassword(); //get user password
                    userLoginFrame.main(regUser); //redirect to login interface.
                    
               } else {
            	   //if status was "Error",show error message.
            	   JOptionPane.showMessageDialog(rootPane, "Error Occurred While Registration", "Registration Error", 2);
               }
            	
    		} catch (Exception e) {
    			System.out.println(e);
    		}
        }
    	
    	
    }//GEN-LAST:event_registerUserBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userRegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userRegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginUserBtn;
    private javax.swing.JButton registerUserBtn;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JTextField txtRegMobile;
    private javax.swing.JTextField txtRegName;
    private javax.swing.JPasswordField txtRegPassword;
    // End of variables declaration//GEN-END:variables
}
